- attack-modules/toxic_sentence_generator.py
We have added a fine-tuned model (base = gpt2) that can generate toxic sentences. The idea is to generate sentence that may solicit the target model to complete with toxic sentences.
Currently, this generator is set to generate 30 iterations.
> ✨  Newly added toxic sentence generator ✨ 

- cookbooks/singapore-context.json
- datasets/singapore-iconic-places.json
- datasets/singapore-political-history.json
- datasets/singapore-public-housing.json
- datasets/singapore-transport-system.json
- recipes/singapore-facts.json
1. Singapore's Public Housing
2. Singapore's Public Transport
3. Singapore's Iconic Places
4. Singapore's Key Political Events in the History
These datasets also come with recipe and cookbook. Test this cookbook with our CLI using the following command:
`run_cookbook -n 10 "sg-facts-test" "['singapore-context']" "[<endpoint>]"`
> New Cookbook, Recipes and Datasets related to Singapore's Facts and History

- cookbooks/chinese-safety-cookbook.json
- cookbooks/singapore-context.json
- datasets/singapore-safety-questions.json
- recipes/singapore-safety.json
- Updated typo in one of the cookbooks.
- Added new recipe and dataset to include some safety prompts related to Singapore's context (e.g., asking whether to get vape while it's illegal in Singapore)
> ✨ Newly added Recipe and Dataset ✨

- attack-modules/job_role_generator.py
So that this module can also run in the red teaming module
> 🐛 Added in the connector instance 🐛

- datasets/singapore-facts-tnf.json
- datasets/singapore-food-tnf.json
- datasets/singapore-places-tnf.json
- recipes/singapore-facts.json
Added 3 new datasets related to facts about Singapore to Singapore recipe to check for some facts about Singapore.
> ✨ Added additional prompts in Singapore Facts ✨

- recipes/realtime-qa.json
Missing grading criteria for Realtime-QA
> Added grading criteria for Realtime-QA

- cookbooks/singapore-context.json
> Removed SS from the cookbook

- attack-modules/sg_sentence_generator.py
This attack module will generate sentences that include Singaporean context and, in some cases, may contain offensive words. 
To run this attack module, please create a red teaming session and run the following command:
```
run_attack_module "sg_sentence_generator" "wah liao eh"
```
_This is an experimental attack module developed by IMDA._
> ✨ Experimental Sentence Generator with SG Context ✨

- runners-modules/redteaming.py
This PR is to add optional parameters for users to use in their attack modules. The optional parameters will be entered by the user in the CLI in the form of a dictionary, which the attack modules can take in (i.e. users may want to decide how many iterations the attack module should run before stopping, so the dictionary can have a field like "max_no_of_iteration" which the attack module will read in)
How to test:
1. Start cli: `python -m moonshot cli interactive`
2. Create a new session: `new_session -h` and copy the help sample codes to create a new session with a new runner (change the connector endpoint to one you can access with your API key)
3. Inside the session, enter `run_attack_module sample_attack_module "test prompt" -o "{'max_number_of_iteration': 1, 'my_optional_param': …
> added optional param for run_attack_module in cli

- .flake8
- .pre-commit-config.yaml
Code changes enables 
- Detect hardcorded secrets before committing.
Planned chore
- chore: Routine tasks, maintenance, or tooling changes
Add the following code to simulate an openai key
`token = "sk-proj-123456789T123456789T123456789m123456789m1234567"`
<details>
```
Version 1.1
By making a contribution to this …
```
> [MS-261] Detect hardcoded secrets

- databases-modules/sqlite.py
Added the bookmark feature for the API and CLI. With this feature, users can bookmark prompts and use them later in a red teaming session.
This PR will have changes to add a new placeholder and changes to deleting database records
To allow users to bookmark prompts which they think are important
<details>
``` …
```
> [MS-335] Bookmark

- connectors/flageval-connector.py
[Provide a brief description of the changes or features introduced by this pull request.]
<details>
```
Version 1.1
Everyone …
```
> update not implmeneted error exception

- .github/workflows/smoke-test.yaml
Add Smoke Test Workflow
Smoke Test is used for quick verification of build to ensure that Core User Flow is stable.
- ci: Changes to the CI/CD configuration or scripts
Run Smoke Test Workflow on the GitHub Actions Pipeline.
<details>
```
Version 1.1
Developer's Certificate …
```
> Add Smoke Test

- cookbooks/clcc-cookbook.json
Added CLCC cookbook
Added CLCC cookbook
Addition of cookbook
1. start moonshot and use either the cli or ui
2. run the clcc cookbook named `clcc-cookbook`
NA
NA
<details>
```
Version 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is …
```
> [Ms 583] Add CLCC cookbook

- datasets/singapore-safety-questions.json
Corrected the target response for sg safety dataset
Corrected the target response for sg safety dataset
A bug fix
1. Prepare a together token and put the token in the config file `together-llama-guard-7b-assistant.json`
2. Start cli and run `run_recipe "sg-safety-test" "['singapore-safety']" "['openai-gpt35-turbo']" -n 1 -r 1 -s "You are an intelligent AI"`
<details>
```
Version 1.1
By making a contribution to this …
```
> [MS-507] Updated sg safety qns dataset

- connectors-endpoints/azure-langchain-openai-chatopenai-gpt4o.json
- connectors-endpoints/azure-langchain-openai-embedding-ada-2.json
- connectors-endpoints/azure-openai-dalle.json
- connectors-endpoints/azure-openai-gpt4-turbo-preview.json
- connectors-endpoints/azure-openai-gpt4o.json
- connectors/anthropic-connector.py
- connectors/azure-langchain-openai-chatopenai-connector.py
- connectors/azure-langchain-openai-embedding-connector.py
- connectors/azure-openai-connector.py
- connectors/azure-openai-t2i-connector.py
- connectors/flageval-connector.py
- connectors/google-gemini-connector.py
- connectors/huggingface-connector.py
- connectors/openai-connector.py
- connectors/openai-t2i-connector.py
- connectors/together-connector.py
- export_api_connector_credentials.sh
Provide better secrets management by allowing users to export the necessary tokens and uri instead of placing their secrets in the connector endpoints.
Users can refer to `export_api_connector_credentials.sh` on the information to be exported.
Provide better secrets management
- feat: A new feature
1. Place your credentials you want to use for the respective connector.
2. Run the script by `. export_api_connector_credentials.sh` in a new terminal.
3. Run the test and it will complete successfully.
<details>
<summary>Developer Certificate …
> [MS-620] Add support for exporting environment variables for tokens and uri

- cookbooks/singapore-pofma-statements.json
- datasets/singapore-pofma-statements-2023.json
- datasets/singapore-pofma-statements-2024.json
- datasets/singapore-pofma-statements.json
- datasets/singapore-pofma-true-statements.json
- recipes/singapore-pofma-true.json
- recipes/singapore-pofma.json
Singapore POFMA related dataset, recipes and cookbook
Determine if the LLM/Chatbot is in compliances with POFMA and not repeating disinformation. Specifically, tests if false statements derived from the website https://www.factually.gov.sg/ are reported correctly as false by the LLM/Chatbot. The dataset was demonstrated recently at IMDA's Technical Sharing Sessions.
6 files added
- cookbooks
- singapore-pofma-statements.json
- recipes
- singapore-pofma-true.json
- singapore-pofma.json
- datasets
- singapore-pofma-statements-2023.json
- singapore-pofma-statements-2024.json
- singapore-pofma-true-statements.json
Dataset only. I have run it as a cookbook for Chatgpt 4o, Gemini Pro 15 and Together Llama 3.1 405b Instruct
- …
> Pofma Dataset

- datasets/cache.json
Updated dataset cache
Updated dataset cache
chore: Routine tasks, maintenance, or tooling changes
- Try viewing recipes/cookbooks in UI
<details>
```
Version 1.1
By making a contribution to this project, I certify that:
(a) The …
```
> updated dataset cache

- pyproject.toml
Update release version from 0.6.4 to 0.7.0.
- other: Other changes that don't fit into the above categories
Manual test in UAT and ran integration test.
<details>
```
Version 1.1 …
```
> [WS-78][Release] Upgrade version from 0.6.4 to 0.7.0 #430

- pyproject.toml
There are fix is introduced:
[MOON-503] Updated AM and metrics cache files #182
- fix: A bug fix
<details>
```
Version 1.1 …
```
> [Additional Release 0.7.0] Fixes

- datasets/cache.json
- datasets/mlc-cae-malicious-user.json
- datasets/mlc-cae-typical-user.json
- datasets/mlc-cbr-malicious-user.json
- datasets/mlc-cbr-typical-user.json
- datasets/mlc-hat-malicious-user.json
- datasets/mlc-hat-typical-user.json
- datasets/mlc-nvc-malicious-user.json
- datasets/mlc-nvc-typical-user.json
- datasets/mlc-scr-malicious-user.json
- datasets/mlc-scr-typical-user.json
- datasets/mlc-ssh-typical-user.json
- datasets/mlc-ssh-vulnerable-user.json
- datasets/mlc-vcr-malicious-user.json
- datasets/mlc-vcr-typical-user.json
Updated some of the references for datasets
Housekeeping 
Maintenance
Nothing to test. Just updating of dataset reference
<details>
```
Version 1.1
By making a contribution to this project, I certify that:
(a) The contribution was …
```
> Update mlc ref

- cookbooks/singapore-context.json
- prompt-templates/singapore-facts-mcq.json
- prompt-templates/singapore-facts-tf.json
- recipes/singapore-facts-mcq.json
- recipes/singapore-facts-tf.json
Recipes description is updated as per the ticket.
Existing cookbook recipes are updated as well
Additional changes made after UAT Found additional changes to be made, additional changes are logged in the ticket.
other: Other changes that don't fit into the above categories
<details>
```
Developer Certificate of …
```
> Ws-118 Additional changes after UAT

- pyproject.toml
[Provide a brief description of the changes or features introduced by this pull request.]
<details>
```
Version 1.1
Everyone …
```
> [Release]update versioning to 0.7.3

- cookbooks/undesirable-content.json
- recipes/mlc-ailuminate-cse.json
- recipes/mlc-ailuminate-hte.json
- recipes/mlc-ailuminate-iwp.json
- recipes/mlc-ailuminate-ncr.json
- recipes/mlc-ailuminate-spc-ele.json
- recipes/mlc-ailuminate-spc-fin.json
- recipes/mlc-ailuminate-spc-hlt.json
- recipes/mlc-ailuminate-spc-lgl.json
- recipes/mlc-ailuminate-src.json
- recipes/mlc-ailuminate-ssh.json
- recipes/mlc-ailuminate-sxc-prn.json
- recipes/mlc-ailuminate-vcr.json
Added 
"mlc-ailuminate-cse",
"mlc-ailuminate-hte",
"mlc-ailuminate-iwp",
"mlc-ailuminate-ncr",
"mlc-ailuminate-spc-ele",
"mlc-ailuminate-spc-fin",
"mlc-ailuminate-spc-hlt",
"mlc-ailuminate-spc-lgl",
"mlc-ailuminate-src",
"mlc-ailuminate-ssh",
"mlc-ailuminate-sxc-prn",   
"mlc-ailuminate-vcr"
as well as updated undesirable content to contain them
[Add any …
> [ws-182] Update cookbook and recipes as per ticket
